version: '3'
services:
  nginx:
    container_name: ${NGINX_CONTAINER}
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/server/http
      - ./storage/logs/:/var/log/nginx
      - ./public/images:/server/http/public/images
    ports:
      - 9084:80
      - 9043:443
    networks:
      - salary-app
    links:
      - php
      - rabbitmq

  php:
    container_name: ${PHP_CONTAINER}
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/server/http
      - ./var/cache/xdebug:/tmp
      - /home/ateeb/.ssh/:/root/.ssh
      - ./storage/logs/:/var/log/nginx
      - ./public/images:/server/http/public/images
      
    ports:
      - 9000:9000
    networks:
      - salary-app
    links:
      - rabbitmq

  rabbitmq:
    container_name: ${AMQP_CONTAINER}
    image: "rabbitmq:3-management"
    restart: unless-stopped
    hostname: ${AMQP_HOST}
    environment:
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASS}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "9072:15672"
      - "9073:5672"
    networks:
      - salary-app
    tty: true
    command: bash -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"
    expose:
      - '5672'
      - '15672'

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - salary-app

#Docker Networks
networks:
  salary-app:
    name: salary-app
    driver: bridge

